# Generated by Django 4.2.5 on 2023-10-09 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_date', models.DateField(null=True)),
                ('notif_time', models.TimeField(null=True)),
                ('text', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('telp', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=7)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='client.client')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
            options={
                'db_table': 'setting',
            },
        ),
    ]
