# Generated by Django 4.2.5 on 2023-09-23 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('no_wa', models.CharField(max_length=13, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Alamat',
            fields=[
                ('provinsi', models.CharField(max_length=255)),
                ('kota_kab', models.CharField(max_length=255)),
                ('jalan', models.CharField(max_length=255)),
                ('kode_pos', models.CharField(max_length=5)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='client.client')),
            ],
            options={
                'db_table': 'alamat',
            },
        ),
    ]
