# Generated by Django 4.2.5 on 2023-09-24 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=50)),
                ('no_telp_wa', models.CharField(max_length=13)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/profile')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
